version: '3'
services:
  postgress:
    image: "postgres:13"
    container_name: "postgres"
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_USER=usr
      - POSTGRES_DB=demoDB
    networks:
      - network
networks:
  network: