drop table if exists client cascade;
drop table if exists address;
drop table if exists phone;

create table address
(
    id bigint generated by default as identity primary key,
    street varchar(50),
    client_id int8
);
create table phone
(
    id bigint generated by default as identity primary key,
    number varchar(255),
    client_id int8
);

create table client
(
    id bigint generated by default as identity PRIMARY KEY,
    name varchar(50),
    address_id bigint,
    phone_id bigint
);

alter table phone add constraint phone_pk foreign key (client_id) references client;